const offsets = {
  none: 0,
  small: 50,
  medium: 100,
  large: 200,
  extraLarge: 300,
  extraExtraLarge: 400,
  extraExtraExtraLarge: 500,
}

export const images = [
  // top images
  {
    src: '/images/products/crater-buff-chawan/1.jpg',
    x: 100,
    y: 10,
    offsetX: offsets.small,
    offsetY: offsets.large,
    width: 326,
    height: 492,
  },
  {
    src: '/images/products/crater-buff-chawan/1.jpg',
    x: 400,
    y: 500,
    offsetX: offsets.medium,
    offsetY: offsets.none,
    width: 326,
    height: 492,
  },
  {
    src: '/images/products/crater-buff-chawan/1.jpg',
    x: 10,
    y: 50,
    offsetX: offsets.none,
    offsetY: offsets.small,
    width: 326,
    height: 492,
  },
  {
    src: '/images/products/crater-buff-chawan/1.jpg',
    x: 10,
    y: 200,
    offsetX: offsets.large,
    offsetY: offsets.small,
    width: 326,
    height: 492,
  },
  {
    src: '/images/products/crater-buff-chawan/1.jpg',
    x: 500,
    y: 75,
    offsetX: offsets.small,
    offsetY: offsets.extraLarge,
    width: 326,
    height: 492,
  },
  // middle images
  {
    src: '/images/products/crater-buff-chawan/1.jpg',
    x: 600,
    y: 0,
    offsetX: offsets.none,
    offsetY: offsets.extraLarge,
    width: 326,
    height: 492,
  },
  {
    src: '/images/products/crater-buff-chawan/1.jpg',
    x: 700,
    y: 0,
    offsetX: offsets.none,
    offsetY: offsets.extraLarge,
    width: 326,
    height: 492,
  },
  {
    src: '/images/products/crater-buff-chawan/1.jpg',
    x: 700,
    y: 0,
    offsetX: offsets.none,
    offsetY: offsets.extraLarge,
    width: 492,
    height: 326,
  },
  {
    src: '/images/products/crater-buff-chawan/1.jpg',
    x: 700,
    y: 0,
    offsetX: offsets.none,
    offsetY: offsets.extraLarge,
    width: 492,
    height: 326,
  },
  {
    src: '/images/products/crater-buff-chawan/1.jpg',
    x: 700,
    y: 0,
    offsetX: offsets.none,
    offsetY: offsets.extraLarge,
    width: 492,
    height: 326,
  },
  {
    src: '/images/products/crater-buff-chawan/1.jpg',
    x: 700,
    y: 0,
    offsetX: offsets.none,
    offsetY: offsets.extraLarge,
    width: 492,
    height: 326,
  },
  {
    src: '/images/products/crater-buff-chawan/1.jpg',
    x: 700,
    y: 0,
    offsetX: offsets.none,
    offsetY: offsets.extraLarge,
    width: 492,
    height: 326,
  },
  {
    src: '/images/products/crater-buff-chawan/1.jpg',
    x: 700,
    y: 0,
    offsetX: offsets.none,
    offsetY: offsets.extraLarge,
    width: 492,
    height: 326,
  },
  {
    src: '/images/products/crater-buff-chawan/1.jpg',
    x: 700,
    y: 0,
    offsetX: offsets.none,
    offsetY: offsets.extraLarge,
    width: 492,
    height: 326,
  },
  {
    src: '/images/products/crater-buff-chawan/1.jpg',
    x: 700,
    y: 0,
    offsetX: offsets.none,
    offsetY: offsets.extraLarge,
    width: 492,
    height: 326,
  },
]
