export const getImages = (width, height) => {
  console.log('wudth', width)
  return [
    {
      src: '/images/investigation/7.jpg',
      width: 200,
      height: 300,
      grid: 1,
      offsetX: 500,
      offsetY: 500,
      column: 1,
      row: 2,
    },
    {
      src: '/images/investigation/19.jpg',
      width: 225,
      height: 150,
      grid: 1,
      offsetX: 0,
      offsetY: 500,
      column: 1,
      row: 3,
    },
    {
      src: '/images/investigation/30.jpg',
      width: 300,
      height: 200,
      grid: 1,
      offsetX: -350,
      offsetY: 550,
      column: 4,
      row: 3,
    },
    {
      src: '/images/investigation/1.jpg',
      width: 472,
      height: 258,
      grid: 1,
      offsetX: -800,
      offsetY: 800,
      column: 0,
      row: 1,
    },
    {
      src: '/images/investigation/21.jpg',
      width: 300,
      height: 200,
      grid: 1,
      offsetX: -700,
      offsetY: 400,
      column: 4,
      row: 3,
    },
    {
      src: '/images/investigation/9.jpg',
      width: 151,
      height: 141,
      grid: 1,
      offsetX: 0,
      offsetY: 0,
      column: 3,
      row: 2,
    },
    {
      src: '/images/investigation/2.jpg',
      width: 211,
      height: 145,
      grid: 1,
      offsetX: 350,
      offsetY: 200,
      column: 1,
      row: 1,
    },
    {
      src: '/images/investigation/23.jpg',
      width: 500,
      height: 333,
      grid: 1,
      offsetX: 940,
      offsetY: 20,
      column: 4,
      row: 3,
    },
    {
      src: '/images/investigation/31.jpg',
      width: 360,
      height: 240,
      grid: 1,
      offsetX: 1600,
      offsetY: 0,
      column: 4,
      row: 3,
    },
    {
      src: '/images/investigation/35.jpg',
      width: 200,
      height: 300,
      grid: 1,
      offsetX: 0,
      offsetY: 500,
      column: 4,
      row: 3,
    },
    {
      src: '/images/investigation/26.jpg',
      width: 300,
      height: 200,
      grid: 1,
      offsetX: 250,
      offsetY: 400,
      column: 4,
      row: 3,
    },
    {
      src: '/images/investigation/34.jpg',
      width: 390,
      height: 260,
      grid: 2,
      offsetX: 500,
      offsetY: 500,
      column: 4,
      row: 3,
    },
    {
      src: '/images/investigation/8.jpg',
      width: 171,
      height: 222,
      grid: 2,
      offsetX: 0,
      offsetY: 500,
      column: 2,
      row: 2,
    },
    {
      src: '/images/investigation/14.jpg',
      width: 165,
      height: -350,
      grid: 2,
      offsetX: -350,
      offsetY: 550,
      column: 3,
      row: 3,
    },
    {
      src: '/images/investigation/22.jpg',
      width: 300,
      height: 200,
      grid: 2,
      offsetX: -800,
      offsetY: 800,
      column: 4,
      row: 3,
    },
    {
      src: '/images/investigation/29.jpg',
      width: 510,
      height: 340,
      grid: 2,
      offsetX: -700,
      offsetY: 400,
      column: 4,
      row: 3,
    },
    {
      src: '/images/investigation/6.jpg',
      width: 276,
      height: 290,
      grid: 2,
      offsetX: 0,
      offsetY: 0,
      column: 0,
      row: 2,
    },
    {
      src: '/images/investigation/27.jpg',
      width: 300,
      height: 200,
      grid: 2,
      offsetX: 350,
      offsetY: 200,
      column: 4,
      row: 3,
    },
    {
      src: '/images/investigation/20.jpg',
      width: 214,
      height: 142,
      grid: 2,
      offsetX: 940,
      offsetY: 20,
      column: 4,
      row: 3,
    },
    {
      src: '/images/investigation/17.jpg',
      width: 150,
      height: 100,
      grid: 2,
      offsetX: 300,
      offsetY: 0,
      column: 4,
      row: 3,
    },
    {
      src: '/images/investigation/18.jpg',
      width: 214,
      height: 142,
      grid: 2,
      offsetX: 0,
      offsetY: 500,
      column: 4,
      row: 3,
    },
    {
      src: '/images/investigation/28.jpg',
      width: 420,
      height: 280,
      grid: 2,
      offsetX: 250,
      offsetY: 400,
      column: 4,
      row: 3,
    },
    {
      src: '/images/investigation/10.jpg',
      width: 202,
      height: 110,
      grid: 2,
      offsetX: 500,
      offsetY: 500,
      column: 4,
      row: 2,
    },
    {
      src: '/images/investigation/13.jpg',
      width: 212,
      height: 197,
      grid: 2,
      offsetX: 500,
      offsetY: 400,
      column: 2,
      row: 3,
    },
  ]
}
