// 3 sections
// a, b, c
// a: -window.innerwidth
// b: window.innerwidth / 2
// c: window.innerwidth * 2
// each image will be relative to its section and will use ofssetX and offsetY to offset it from each 0,0

export const getImages = (width, height) => {
  console.log('wudth', width)
  return [
    {
      src: '/images/investigation/7.jpg',
      width: 200,
      height: 300,
      grid: 1,
      offsetX: 500,
      offsetY: 500,
      column: 1,
      row: 2,
    },
    {
      src: '/images/investigation/19.jpg',
      width: 225,
      height: 150,
      grid: 1,
      offsetX: 200,
      offsetY: 500,
      column: 1,
      row: 3,
    },
    // {
    //   src: '/images/investigation/30.jpg',
    //   width: 300,
    //   height: 200,
    //   grid: 5,
    //   offsetX: -350,
    //   offsetY: 550,
    //   column: 4,
    //   row: 3,
    // },
    // {
    //   src: '/images/investigation/1.jpg',
    //   width: 472,
    //   height: 258,
    //   grid: 5,
    //   offsetX: -800,
    //   offsetY: 800,
    //   column: 0,
    //   row: 1,
    // },
    // {
    //   src: '/images/investigation/21.jpg',
    //   width: 300,
    //   height: 200,
    //   grid: 5,
    //   offsetX: -700,
    //   offsetY: 400,
    //   column: 4,
    //   row: 3,
    // },
    // {
    //   src: '/images/investigation/9.jpg',
    //   width: 151,
    //   height: 141,
    //   grid: 5,
    //   offsetX: 0,
    //   offsetY: 0,
    //   column: 3,
    //   row: 2,
    // },
    // {
    //   src: '/images/investigation/2.jpg',
    //   width: 211,
    //   height: 145,
    //   grid: 5,
    //   offsetX: 350,
    //   offsetY: 200,
    //   column: 1,
    //   row: 1,
    // },
    // {
    //   src: '/images/investigation/23.jpg',
    //   width: 500,
    //   height: 333,
    //   grid: 5,
    //   offsetX: 940,
    //   offsetY: 20,
    //   column: 4,
    //   row: 3,
    // },
    // {
    //   src: '/images/investigation/31.jpg',
    //   width: 360,
    //   height: 240,
    //   grid: 5,
    //   offsetX: 1600,
    //   offsetY: 0,
    //   column: 4,
    //   row: 3,
    // },
    // {
    //   src: '/images/investigation/35.jpg',
    //   width: 200,
    //   height: 300,
    //   grid: 5,
    //   offsetX: 0,
    //   offsetY: 500,
    //   column: 4,
    //   row: 3,
    // },
    // {
    //   src: '/images/investigation/26.jpg',
    //   width: 300,
    //   height: 200,
    //   grid: 5,
    //   offsetX: 250,
    //   offsetY: 400,
    //   column: 4,
    //   row: 3,
    // },
    // {
    //   src: '/images/investigation/34.jpg',
    //   width: 390,
    //   height: 260,
    //   grid: 5,
    //   offsetX: 600,
    //   offsetY: 380,
    //   column: 4,
    //   row: 3,
    // },
    // {
    //   src: '/images/investigation/8.jpg',
    //   width: 171,
    //   height: 222,
    //   grid: 5,
    //   offsetX: 1100,
    //   offsetY: 500,
    //   column: 2,
    //   row: 2,
    // },
    // {
    //   src: '/images/investigation/14.jpg',
    //   width: 165,
    //   height: 128,
    //   grid: 5,
    //   offsetX: 1500,
    //   offsetY: 320,
    //   column: 3,
    //   row: 3,
    // },
    // {
    //   src: '/images/investigation/22.jpg',
    //   width: 300,
    //   height: 200,
    //   grid: 5,
    //   offsetX: 80,
    //   offsetY: 1000,
    //   column: 4,
    //   row: 3,
    // },
    // {
    //   src: '/images/investigation/29.jpg',
    //   width: 510,
    //   height: 340,
    //   grid: 5,
    //   offsetX: 400,
    //   offsetY: 700,
    //   column: 4,
    //   row: 3,
    // },
    // {
    //   src: '/images/investigation/6.jpg',
    //   width: 276,
    //   height: 290,
    //   grid: 5,
    //   offsetX: 980,
    //   offsetY: 700,
    //   column: 0,
    //   row: 2,
    // },
    // {
    //   src: '/images/investigation/27.jpg',
    //   width: 300,
    //   height: 200,
    //   grid: 5,
    //   offsetX: 1300,
    //   offsetY: 750,
    //   column: 4,
    //   row: 3,
    // },
    // {
    //   src: '/images/investigation/20.jpg',
    //   width: 214,
    //   height: 142,
    //   grid: 5,
    //   offsetX: 1600,
    //   offsetY: 520,
    //   column: 4,
    //   row: 3,
    // },
    // {
    //   src: '/images/investigation/17.jpg',
    //   width: 150,
    //   height: 100,
    //   grid: 5,
    //   offsetX: 1650,
    //   offsetY: 1000,
    //   column: 4,
    //   row: 3,
    // },
    // {
    //   src: '/images/investigation/18.jpg',
    //   width: 214,
    //   height: 142,
    //   grid: 5,
    //   offsetX: 1700,
    //   offsetY: 870,
    //   column: 4,
    //   row: 3,
    // },
    // {
    //   src: '/images/investigation/28.jpg',
    //   width: 420,
    //   height: 280,
    //   grid: 5,
    //   offsetX: 2050,
    //   offsetY: 700,
    //   column: 4,
    //   row: 3,
    // },
    // {
    //   src: '/images/investigation/10.jpg',
    //   width: 202,
    //   height: 110,
    //   grid: 5,
    //   offsetX: 2000,
    //   offsetY: 500,
    //   column: 4,
    //   row: 2,
    // },
    // {
    //   src: '/images/investigation/13.jpg',
    //   width: 212,
    //   height: 197,
    //   grid: 5,
    //   offsetX: 2300,
    //   offsetY: 400,
    //   column: 2,
    //   row: 3,
    // },
  ]
}
