const offset = {
  x: {
    one: 0,
    two: 10,
    three: 20,
    four: 35,
    five: 50,
  },
  y: {
    one: 0,
    two: 50,
    three: 75,
    four: 100,
    five: 150,
  },
}

const dimensions = {
  portrait: {
    small: {
      width: 320,
      height: 480,
    },
    medium: {
      width: 480,
      height: 720,
    },
    large: {
      width: 640,
      height: 960,
    },
  },
  landscape: {
    small: {
      width: 480,
      height: 320,
    },
    medium: {
      width: 640,
      height: 426,
    },
    large: {
      width: 960,
      height: 640,
    },
  },
}

export const plates = [
  {
    id: '118',
    sku: 'crater-buff-chawan',
    pre: 'crater buff chawan',
    date: '2022',
    offsetX: offset.x.two,
    offsetY: offset.y.five,
    ...dimensions.portrait.medium,
    thumbnail: '/images/products/crater-buff-chawan/1.jpg',
    imageCarousel: ['/images/products/crater-buff-chawan/1.jpg'],
    description:
      'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
  },
  {
    id: '118',
    sku: 'porcelain-incision-bowls',
    pre: 'porcelain incision bowls',
    date: '2022',
    offsetX: offset.x.two,
    offsetY: offset.one,
    ...dimensions.portrait.medium,
    thumbnail: '/images/products/porcelain-incision-bowls/1.jpg',
    imageCarousel: [
      '/images/products/porcelain-incision-bowls/1.jpg',
      '/images/products/porcelain-incision-bowls/2.jpg',
      '/images/products/porcelain-incision-bowls/3.jpg',
      '/images/products/porcelain-incision-bowls/4.jpg',
      '/images/products/porcelain-incision-bowls/5.jpg',
      '/images/products/porcelain-incision-bowls/6.jpg',
      '/images/products/porcelain-incision-bowls/7.jpg',
    ],
    description:
      'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
  },
  {
    id: '118',
    sku: 'mixed-clay-bowls',
    pre: 'mixed clay bowls',
    date: '2022',
    offsetX: offset.x.one,
    offsetY: offset.y.five,
    ...dimensions.portrait.medium,
    thumbnail: '/images/products/mixed-clay-bowls/1.jpg',
    imageCarousel: [
      '/images/products/mixed-clay-bowls/1.jpg',
      '/images/products/mixed-clay-bowls/2.jpg',
      '/images/products/mixed-clay-bowls/3.jpg',
      '/images/products/mixed-clay-bowls/4.jpg',
      '/images/products/mixed-clay-bowls/5.jpg',
      '/images/products/mixed-clay-bowls/6.jpg',
      '/images/products/mixed-clay-bowls/7.jpg',
      '/images/products/mixed-clay-bowls/8.jpg',
      '/images/products/mixed-clay-bowls/9.jpg',
      '/images/products/mixed-clay-bowls/10.jpg',
    ],
    description:
      'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
  },
  {
    id: '118',
    sku: 'granite-bowl',
    pre: 'Mixed glazes and oxides',
    date: '2022',
    offsetX: offset.x.two,
    offsetY: offset.y.five,
    ...dimensions.landscape.medium,
    thumbnail: '/images/products/granite-nude-bowls/1.jpg',
    imageCarousel: [
      '/images/products/granite-nude-bowls/1.jpg',
      '/images/products/granite-nude-bowls/3.jpg',
      '/images/products/granite-nude-bowls/4.jpg',
      '/images/products/granite-nude-bowls/5.jpg',
      '/images/products/granite-nude-bowls/6.jpg',
      '/images/products/granite-nude-bowls/7.jpg',
      '/images/products/granite-nude-bowls/2.jpg',
      '/images/products/granite-nude-bowls/8.jpg',
      '/images/products/granite-nude-bowls/9.jpg',
      '/images/products/granite-nude-bowls/10.jpg',
      '/images/products/granite-nude-bowls/11.jpg',
      '/images/products/granite-nude-bowls/15.jpg',
    ],
    description:
      'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
  },
  {
    id: '118',
    sku: 'granite-nude-bowl',
    pre: 'Mixed glazes and oxides',
    date: '2022',
    offsetX: offset.x.four,
    offsetY: offset.y.four,
    ...dimensions.landscape.medium,
    thumbnail: '/images/products/granite-nude-bowls/12.jpg',
    imageCarousel: [
      '/images/products/granite-nude-bowls/12.jpg',
      '/images/products/granite-nude-bowls/13.jpg',
      '/images/products/granite-nude-bowls/3.jpg',
      '/images/products/granite-nude-bowls/15.jpg',
      '/images/products/granite-nude-bowls/16.jpg',
    ],
    description:
      'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
  },
  {
    id: '118',
    sku: 'black-moon-bowl',
    pre: 'black moon bowl',
    date: '2022',
    offsetX: offset.x.three,
    offsetY: offset.y.three,
    ...dimensions.landscape.medium,
    thumbnail: '/images/products/black-moon-bowl/1.jpg',
    imageCarousel: [
      '/images/products/black-moon-bowl/1.jpg',
      '/images/products/black-moon-bowl/2.jpg',
      '/images/products/black-moon-bowl/3.jpg',
    ],
    description:
      'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
  },
  {
    id: '118',
    sku: 'crank-buff-chawan',
    pre: 'crank buff chawan',
    date: '2022',
    offsetX: offset.x.two,
    offsetY: offset.y.two,
    ...dimensions.landscape.medium,
    thumbnail: '/images/products/crank-buff-chawan/1.jpg',
    imageCarousel: ['/images/products/crank-buff-chawan/1.jpg'],
    description:
      'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
  },
  {
    id: '118',
    sku: 'crater-reactive-chawan',
    pre: 'crater reactive chawan',
    date: '2022',
    offsetX: offset.x.two,
    offsetY: offset.y.two,
    ...dimensions.portrait.medium,
    thumbnail: '/images/products/crater-reactive-chawan/1.jpg',
    imageCarousel: [
      '/images/products/crater-reactive-chawan/1.jpg',
      '/images/products/crater-reactive-chawan/2.jpg',
      '/images/products/crater-reactive-chawan/3.jpg',
      '/images/products/crater-reactive-chawan/4.jpg',
    ],
    description:
      'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
  },
  {
    id: '118',
    sku: 'metal-terracotta-chawan',
    pre: 'metal terracotta chawan',
    date: '2022',
    offsetX: offset.x.two,
    offsetY: offset.y.two,
    ...dimensions.portrait.medium,
    thumbnail: '/images/products/metal-terracotta-chawan/1.jpg',
    imageCarousel: [
      '/images/products/metal-terracotta-chawan/1.jpg',
      '/images/products/metal-terracotta-chawan/2.jpg',
      '/images/products/metal-terracotta-chawan/3.jpg',
      '/images/products/metal-terracotta-chawan/4.jpg',
      '/images/products/metal-terracotta-chawan/5.jpg',
      '/images/products/metal-terracotta-chawan/6.jpg',
      '/images/products/metal-terracotta-chawan/7.jpg',
      '/images/products/metal-terracotta-chawan/8.jpg',
      '/images/products/metal-terracotta-chawan/9.jpg',
      '/images/products/metal-terracotta-chawan/10.jpg',
      '/images/products/metal-terracotta-chawan/11.jpg',
      '/images/products/metal-terracotta-chawan/12.jpg',
      '/images/products/metal-terracotta-chawan/13.jpg',
      '/images/products/metal-terracotta-chawan/14.jpg',
    ],
    description:
      'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
  },
  {
    id: '118',
    sku: 'sake-cups',
    pre: 'sake cups',
    date: '2022',
    offsetX: offset.x.three,
    offsetY: offset.y.five,
    ...dimensions.landscape.medium,
    thumbnail: '/images/products/sake-cups/1.jpg',
    imageCarousel: [
      '/images/products/sake-cups/1.jpg',
      '/images/products/sake-cups/2.jpg',
    ],
    description:
      'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
  },
  {
    id: '118',
    sku: 'sand-plates',
    pre: 'sand plates',
    date: '2022',
    offsetX: offset.x.two,
    offsetY: offset.y.two,
    ...dimensions.portrait.medium,
    thumbnail: '/images/products/sand-plates/1.jpg',
    imageCarousel: [
      '/images/products/sand-plates/1.jpg',
      '/images/products/sand-plates/2.jpg',
    ],
    description:
      'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
  },
  {
    id: '118',
    sku: 'surface-of-the-moon',
    pre: 'surface of the moon',
    date: '2022',
    offsetX: offset.x.one,
    offsetY: offset.y.three,
    ...dimensions.portrait.medium,
    thumbnail: '/images/products/surface-of-the-moon/1.jpg',
    imageCarousel: [
      '/images/products/surface-of-the-moon/1.jpg',
      '/images/products/surface-of-the-moon/2.jpg',
      '/images/products/surface-of-the-moon/3.jpg',
      '/images/products/surface-of-the-moon/4.jpg',
      '/images/products/surface-of-the-moon/5.jpg',
      '/images/products/surface-of-the-moon/6.jpg',
      '/images/products/surface-of-the-moon/7.jpg',
      '/images/products/surface-of-the-moon/8.jpg',
      '/images/products/surface-of-the-moon/9.jpg',
      '/images/products/surface-of-the-moon/10.jpg',
      '/images/products/surface-of-the-moon/11.jpg',
      '/images/products/surface-of-the-moon/12.jpg',
      '/images/products/surface-of-the-moon/13.jpg',
      '/images/products/surface-of-the-moon/14.jpg',
      '/images/products/surface-of-the-moon/15.jpg',
      '/images/products/surface-of-the-moon/16.jpg',
      '/images/products/surface-of-the-moon/16.jpg',
      '/images/products/surface-of-the-moon/17.jpg',
      '/images/products/surface-of-the-moon/18.jpg',
      '/images/products/surface-of-the-moon/19.jpg',
      '/images/products/surface-of-the-moon/20.jpg',
      '/images/products/surface-of-the-moon/21.jpg',
      '/images/products/surface-of-the-moon/22.jpg',
      '/images/products/surface-of-the-moon/23.jpg',
    ],
    description:
      'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
  },
  {
    id: '118',
    sku: 'terracotta-crater-chawan',
    pre: 'terracotta crater chawan',
    date: '2022',
    offsetX: offset.x.two,
    offsetY: offset.y.five,
    ...dimensions.portrait.medium,
    thumbnail: '/images/products/terracotta-crater-chawan/1.jpg',
    imageCarousel: [
      '/images/products/terracotta-crater-chawan/1.jpg',
      '/images/products/terracotta-crater-chawan/2.jpg',
      '/images/products/terracotta-crater-chawan/3.jpg',
      '/images/products/terracotta-crater-chawan/4.jpg',
      '/images/products/terracotta-crater-chawan/5.jpg',
      '/images/products/terracotta-crater-chawan/6.jpg',
      '/images/products/terracotta-crater-chawan/7.jpg',
    ],
    description:
      'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
  },
  {
    id: '118',
    sku: 'terracotta-reactive-chawan',
    pre: 'terracotta reactive chawan',
    date: '2022',
    offsetX: offset.x.three,
    offsetY: offset.y.four,
    ...dimensions.portrait.medium,
    thumbnail: '/images/products/terracotta-reactive-chawan/1.jpg',
    imageCarousel: [
      '/images/products/terracotta-reactive-chawan/1.jpg',
      '/images/products/terracotta-reactive-chawan/2.jpg',
      '/images/products/terracotta-reactive-chawan/3.jpg',
      '/images/products/terracotta-reactive-chawan/4.jpg',
      '/images/products/terracotta-reactive-chawan/5.jpg',
      '/images/products/terracotta-reactive-chawan/6.jpg',
      '/images/products/terracotta-reactive-chawan/7.jpg',
      '/images/products/terracotta-reactive-chawan/8.jpg',
    ],
    description:
      'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
  },
]
